name: Rotate GHCR imagePullSecrets

on:
  workflow_dispatch:
    inputs:
      namespaces:
        description: "Comma-separated namespaces (REQUIRED)"
        required: true
jobs:
  rotate-secret:
    runs-on: ubuntu-latest

    environment:
      name: prod

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Prepare namespace list
        run: |
          echo "${{ inputs.namespaces }}" | tr ',' ' ' > ns.txt
          echo "Namespaces to update:"
          cat ns.txt

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GKE_KEY }}'

      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: your-cluster-name
          location: cluster-region

      - name: Update GHCR secret in namespaces
        run: |
          for ns in $(cat ns.txt); do
            echo "Updating ghcr-secret in namespace: $ns"

            kubectl create secret docker-registry ghcr-secret \
              --docker-server=ghcr.io \
              --docker-username="${{ secrets.GHCR_USERNAME }}" \
              --docker-password="${{ secrets.GHCR_PAT }}" \
              --docker-email="your-email" \
              -n "$ns" \
              --dry-run=client -o yaml | kubectl apply -f -
          done